version: "3.9"

services:
  livraria-postgres:
    container_name: livraria-db
    image: postgres:13
    environment:
      - POSTGRES_USER=dba
      - POSTGRES_PASSWORD=dba
      - POSTGRES_DB=livrariaDb
    ports:
      - "5432:5432"  # Expondo o Postgres na porta 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persistindo dados no host
    networks:
      - livraria_net
    restart: always

  backend:
    container_name: livraria-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expondo a API na porta 3000
    environment:
      - PORT=3000
      - DB_HOST=livraria-postgres
      - DB_PORT=5432
      - DB_USER=dba
      - DB_PASS=dba
      - DB_NAME=livrariaDb
    depends_on:
      - livraria-postgres
    networks:
      - livraria_net
    restart: always

  pgadmin:
    container_name: livraria-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dba@mail.com  # Qualquer e-mail fictício
      - PGADMIN_DEFAULT_PASSWORD=dba
    ports:
      - "5050:80"  # Acessar PGAdmin via http://localhost:5050
    depends_on:
      - livraria-postgres
    networks:
      - livraria_net
    restart: always

networks:
  livraria_net:
    driver: bridge
